import * as github from '@actions/github';
import * as core from '@actions/core';

import type { PRResult } from './types.js';
import { GitHubAPIError } from './errors.js';

/**
 * Creates a new pull request or updates an existing one.
 *
 * @param targetRepo - Target repository in owner/repo format
 * @param token - GitHub token for authentication
 * @param branchName - Branch name for the PR
 * @param packageName - Name of the package being updated
 * @param version - New version of the package
 * @returns Result containing PR URL, number, and whether it was created
 * @throws GitHubAPIError if PR creation/update fails
 *
 * @example
 * const result = await createOrUpdatePR(
 *   'shini4i/nixpkgs',
 *   'ghp_token',
 *   'chore/my-package-v1.0.0',
 *   'my-package',
 *   '1.0.0'
 * );
 */
export async function createOrUpdatePR(
  targetRepo: string,
  token: string,
  branchName: string,
  packageName: string,
  version: string
): Promise<PRResult> {
  const octokit = github.getOctokit(token);
  const [owner, repo] = targetRepo.split('/');

  if (owner === undefined || repo === undefined) {
    throw new GitHubAPIError(`Invalid target repository format: ${targetRepo}`);
  }

  const title = `bump ${packageName} version to ${version}`;
  const body = `## Summary

- Updates \`${packageName}\` to version \`${version}\`
- Auto-generated by nixpkgs-updater action

## Changes

- Updated \`version\` field
- Updated \`rev\` field
- Updated \`sha256\` hash
`;

  try {
    // Check for existing PR from this branch
    const { data: existingPRs } = await octokit.rest.pulls.list({
      owner,
      repo,
      head: `${owner}:${branchName}`,
      state: 'open',
    });

    if (existingPRs.length > 0) {
      // Update existing PR
      const existingPR = existingPRs[0];

      if (existingPR === undefined) {
        throw new GitHubAPIError('Unexpected: existing PR list is empty after length check');
      }

      core.info(`Found existing PR #${String(existingPR.number)}, updating...`);

      await octokit.rest.pulls.update({
        owner,
        repo,
        pull_number: existingPR.number,
        title,
        body,
      });

      return {
        url: existingPR.html_url,
        number: existingPR.number,
        created: false,
      };
    }

    // Create new PR
    const { data: newPR } = await octokit.rest.pulls.create({
      owner,
      repo,
      title,
      body,
      head: branchName,
      base: 'main',
    });

    return {
      url: newPR.html_url,
      number: newPR.number,
      created: true,
    };
  } catch (error) {
    if (error instanceof GitHubAPIError) {
      throw error;
    }
    throw new GitHubAPIError(
      `Failed to create/update PR: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}
